[build]
  command = "npm run build:frontend"
  publish = "packages/frontend/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  # Frontend
  VITE_SUPABASE_URL = "https://nzmzmsmxbiptilzgdmgt.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bXptc214YmlwdGlsemdkbWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MTczODYsImV4cCI6MjA3NjI5MzM4Nn0.kfbv7RDBHRmxjpJZqbvPnFqUDRHwLy9kuGgaSUVW0Oo"
  VITE_BACKEND_URL = "https://jarvis-ai.co"

  # Backend (Netlify Functions)
  FRONTEND_URL = "https://jarvis-ai.co"
  SUPABASE_URL = "https://nzmzmsmxbiptilzgdmgt.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bXptc214YmlwdGlsemdkbWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MTczODYsImV4cCI6MjA3NjI5MzM4Nn0.kfbv7RDBHRmxjpJZqbvPnFqUDRHwLy9kuGgaSUVW0Oo"
  SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bXptc214YmlwdGlsemdkbWd0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDcxNzM4NiwiZXhwIjoyMDc2MjkzMzg2fQ.MbpktlET8hmGz54Zhbsu1JxAKeBFrJ9KGyWV3k3Uy1M"

  # Twitter OAuth
  TWITTER_OAUTH_CLIENT_ID = "QkUtRkh6akFOeGdjdzJME9FeGQ6MTpjaQ"
  TWITTER_OAUTH_CLIENT_SECRET = "gRrdulQs6vOFR4njvIFMIk1ou8OXYp84pLgFxKISKFqe_hW9Zi"

  # Twitter Legacy API
  TWITTER_API_KEY = "i1edmBlxyYs0idXUSs7xUnjtM"
  TWITTER_API_SECRET = "3FYleNLqcvCl4GaqXrYdC7PkakICSuKcqIf2rnH8kvZ4Y0H3la"
  TWITTER_ACCESS_TOKEN = "1978598113255591936-p6y9F1uLQoQM8gE7ru8sDbNEkt6K03"
  TWITTER_ACCESS_TOKEN_SECRET = "FqUgmWdmBHIvckWu0sUVZ4aYXNxqQNWErFgnXVuAsx0In"

  # Stripe
  STRIPE_SECRET_KEY = "sk_test_51SJLCeEKVYJUPWdj1CWbTJx7BXGirx9EujgSXGjCGkprdtR8WS6eEtMNPnngsz0A4nZyJRo3va7YcNzTFSaG2Iuu00FaV1VcDQ"
  STRIPE_WEBHOOK_SECRET = "whsec_YOUR_SECRET_HERE"
  STRIPE_STARTER_PRICE_ID = "price_1SJyd0EKVYJUPWdjNM1XJwta"
  STRIPE_PRO_PRICE_ID = "price_1SJyd1EKVYJUPWdjaer6d3yd"
  STRIPE_ENTERPRISE_PRICE_ID = "price_1SJyd3EKVYJUPWdj0GRgf3VZ"
